FIRE ON FLOOR 5 (DECISION)
- Call 911
  - Kind police officer answers the phone
  - Asks about location/situation
- Run into fire
  - Get burned by flames and pass out
  - DEATH
- Ignore
  - Leave 
  - Go down to ground floor



CALL 911 (DECISION)
- Gets "floor number" question right?
  - YES
    - Gets "# of people in room" right?
      - YES
        - Gets "what happened" right
          - YES
            - Everyone saved
            - No major injuries
            - Mystery solved
            - Hero status
          - NO
            - Everyone saved
            - No major injuries
            - Mystery not solved
      - NO
        - Gets "what happened" right
          - YES
            - Over-estimate
              - Fireman injured
            - Under-estimate
              - Person left behind
            - No major injuries from those saved
            - Mystery solved
          - NO
            - Over-estimate
              - Fireman injured
            - Under-estimate
              - Person left behind
            - No major injuries from those saved
            - Mystery not solved
  - NO
    - Gets "# of people in room" right?
      - YES
        - Gets "what happened" right
          - YES
            - Everyone saved
            - Major injuries
            - Mystery solved
          - NO
            - Everyone saved
            - Major injuries
            - Mystery not solved
      - NO
        - Gets "what happened" right
          - YES
            - Over-estimate
              - Fireman injured
            - Under-estimate
              - Person left behind
            - Major injuries
            - Mystery solved
          - NO
            - Everyone perished
            - Mystery not solved


LEAVE (DECISION)
- Earthquake
  - Go outside?
    - Crushed by tree 
    - DEATH
  - Hide next to bookcase?
    - Flattened by bookshelf
    - DEATH
  - Hide under table?
    - Have blanket?
      - YES
        - Safe
      - NO
        - Safe (minor injuries)
